/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  corePlugins: {
    preflight: false,
  },
  theme: {
    screens: {
      'sm': '640px',
      'md': '768px',
      'lg': '960px',
      'xl': '1280px',
      '2xl': '1440px',
    },
    extend: {
      spacing: {
        '0': '0px',
        '1': 'var(--space-1)',
        '2': 'var(--space-2)',
        '3': 'var(--space-3)',
        '4': 'var(--space-4)',
        '6': 'var(--space-6)',
        '8': 'var(--space-8)',
        'xs': 'var(--space-1)',
        'sm': 'var(--space-2)',
        'md': 'var(--space-3)',
        'lg': 'var(--space-4)',
        'xl': 'var(--space-6)',
        '2xl': 'var(--space-8)',
        '3xl': 'var(--space-12)',
        '4xl': 'var(--space-16)',
      },
      textColor: {
        'primary': 'var(--color-text-primary)',
        'secondary': 'var(--color-text-secondary)',
        'tertiary': 'var(--color-text-tertiary)',
        'accent': 'var(--color-accent)',
        'success': 'var(--color-success)',
        'warning': 'var(--color-warning)',
        'danger': 'var(--color-danger)',
        'error': 'var(--color-danger)',
        'muted': 'var(--color-text-secondary)',
        'bg': 'var(--color-bg)',
        'white': '#FFFFFF',
      },
      backgroundColor: {
        'bg': 'var(--color-bg)',
        'card': 'var(--color-bg-card)',
        'bg-card': 'var(--color-bg-card)',
        'secondary': 'var(--color-bg-secondary)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'tertiary': 'var(--color-bg-tertiary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        'accent': 'var(--color-accent)',
        'accent-subtle': 'var(--color-accent-subtle)',
        'success': 'var(--color-success)',
        'success-subtle': 'var(--color-success-subtle)',
        'warning': 'var(--color-warning)',
        'warning-subtle': 'var(--color-warning-subtle)',
        'danger': 'var(--color-danger)',
        'text-primary': 'var(--color-text-primary)',
        'transparent': 'transparent',
      },
      borderColor: {
        'border': 'var(--color-border)',
        'bg': 'var(--color-bg)',
        'danger': 'var(--color-danger)',
        'transparent': 'transparent',
      },
      borderRadius: {
        'none': '0px',
        'sm': 'var(--radius-sm)',
        'md': 'var(--radius-md)',
        'lg': 'var(--radius-lg)',
        'xl': 'var(--radius-xl)',
        '2xl': 'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      boxShadow: {
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
      },
      fontSize: {
        'xs': 'var(--font-size-xs)',
        'sm': 'var(--font-size-sm)',
        'base': 'var(--font-size-base)',
        'md': 'var(--font-size-md)',
        'lg': 'var(--font-size-lg)',
        'xl': 'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '5xl': 'var(--font-size-3xl)',
      },
      zIndex: {
        '10': '10',
        '20': '20',
      }
    }
  }
}
